// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _14._9._2021_1;

namespace _14._9._2021_1.Migrations
{
    [DbContext(typeof(CSDL))]
    partial class CSDLModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("_14._9._2021_1.LOPSH", b =>
                {
                    b.Property<int>("ID_Lop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameLop")
                        .HasColumnType("longtext");

                    b.HasKey("ID_Lop");

                    b.ToTable("LopSinhVien");
                });

            modelBuilder.Entity("_14._9._2021_1.SV", b =>
                {
                    b.Property<string>("Mssv")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("DTB")
                        .HasColumnType("double");

                    b.Property<int>("ID_Lop")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Mssv");

                    b.HasIndex("ID_Lop");

                    b.ToTable("Sinh Vien");
                });

            modelBuilder.Entity("_14._9._2021_1.SV", b =>
                {
                    b.HasOne("_14._9._2021_1.LOPSH", "lopsh")
                        .WithMany("SVs")
                        .HasForeignKey("ID_Lop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("lopsh");
                });

            modelBuilder.Entity("_14._9._2021_1.LOPSH", b =>
                {
                    b.Navigation("SVs");
                });
#pragma warning restore 612, 618
        }
    }
}
